<a href="https://colab.research.google.com/github/vcetonurface/junkprograms/blob/dwm/naive_bayes_algo.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Naive Bayes

In [39]:
import numpy as np
import pandas as pd

In [40]:
dataset = pd.read_csv('/content/preprocessed.csv')
dataset.dropna(axis=0,inplace=True)
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, 1].values

In [41]:
X

array([[ 0., 24.,  3., ...,  0.,  0.,  1.],
       [ 2.,  1.,  5., ...,  0.,  0.,  0.],
       [ 2.,  9.,  6., ...,  0.,  0.,  0.],
       ...,
       [ 0., 27.,  4., ...,  0.,  0.,  0.],
       [ 0.,  1.,  3., ...,  0.,  0.,  1.],
       [ 2.,  9.,  5., ...,  0.,  0.,  0.]])

In [42]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 0)

In [43]:
print(X_train)

[[ 1. 24.  3. ...  0.  0.  0.]
 [ 0. 18.  6. ...  0.  0.  0.]
 [ 1. 18.  5. ...  0.  0.  0.]
 ...
 [ 1.  3.  3. ...  0.  0.  0.]
 [ 2.  3.  3. ...  0.  0.  0.]
 [ 1.  9.  5. ...  0.  0.  0.]]


In [44]:
print(y_train)

[24 18 18 ...  3  3  9]


In [45]:
print(X_test)

[[ 1. 15.  5. ...  0.  0.  0.]
 [ 1. 21.  5. ...  0.  0.  0.]
 [ 0. 27.  6. ...  0.  1.  0.]
 ...
 [ 1. 18.  5. ...  0.  0.  0.]
 [ 0.  1.  5. ...  0.  0.  0.]
 [ 1.  9.  6. ...  0.  0.  0.]]


In [46]:
print(y_test)

[15 21 27 ... 18  1  9]


In [47]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [48]:
from sklearn.naive_bayes import GaussianNB
classifier = GaussianNB()
classifier.fit(X_train, y_train)

GaussianNB()

In [49]:
print(classifier.predict(sc.transform([[2,24,3,15,20,4,40,20,30,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0]])))

[1]


In [50]:
y_pred = classifier.predict(X_test)


In [51]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[275   1   0   0   0   0   0   0   0   0]
 [  1 220   0   0   0   0   0   0   0   0]
 [  1   0 328   0   0   0   0   0   0   0]
 [  0   0   0 329   0   0   0   0   0   0]
 [  0   0   0   0 229   0   0   0   0   0]
 [  0   0   0   0   0 225   0   0   0   0]
 [  0   0   0   0   0   0 208   0   0   0]
 [  0   0   0   0   0   0   0 308   0   0]
 [  0   0   0   0   0   0   0   0 252   0]
 [  0   0   0   0   0   0   0   0   0 294]]


0.9988768251591165